title: Siddhant Attavar
email: siddhantattavar12@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  SiddhantAttavar

# Build settings
# remote_theme: minima
theme: minima

# Plugins
# plugins:
  # - plugin

# for atom feed
author:
  name: Siddhant Attavar
  email: siddhantattavar12@gmail.com

